class DNA():
    def __init__(self, dnaString):
        self.dnaString = dnaString

    def solve(self) -> list:
        return [self.dnaString.count(letter) for letter in ['A', 'C', 'G', 'T']]
    
    def printSolution(self, solution):
        for num in solution:
            print(str(num) + " ", end="")

dna = DNA("CGCAAATCGGCGCATGGTCTCTCTAGCTACACCTACCGGTACCCGGCCCCGGGAATCGGAAAGACACGTTTGTGGAAATCGGTTGTTAGTAAGTAGCCCTATCTTCCCTAAGCGAAACGAAGCGCCAGTCCCACGGAAGACACTATGCCCATGTTCTGGTAACCTACCGCAAGGTCTTTACGGAAGATTATACTGGATAGGGCGGAATGGCAACAGGAAATATGCGCTCGGCATACTGTCCCGATTGGTGTTCACGCCAACACGGAATCTTTAGTTAAGCTGTCTGGGATTAAAATGCGAGATTCGGTGGCTTAATGATATTGACAACTGCTGATAGAAACTCGCTCAAGCTTGTCTTAGTTTTCGAAGAACAGTGATCTAAATATGGCAGGCAAGTGATCTTCGCTCCTCCGGATCAGCAGGTGTGTCGTTTCGCGTTGAGTCAATGTGGCCGGCTCCTTAAAATCGAAGCCGTTTCACGAGTCGATTGAATGTTGCCTGTGCGCTTCGGAAAGAAGAGACGCAATGGCTAAGAAAAAGGCAGCAGGTGCTAAGATTGTCAAATATAGGCACACTCGTGATTAGCGTTGACTCGCGGTTGGCCTGGTTCGGTCTAGCGTGGGCTGGCCAGAAGCCTTACCACTTTGCTAGATCCACTGCGTACGCGTCCGTGTATACAATGAATCTCGCTTAGAAGAGTCCATCAACGCGTTACTCCAATGATCACCCCCTGACGACGGGAACTTGGACAGTATCAGGGAGAGTGCGGATTTCCAAGACGTTAGGGACCCAGCAGTCCTGTTTGGCATAACCCGAAAAACCCAAGGACATCTCATAAGATTAGTTTTCTGTACGGTCTTGACCACCTTTAATGACTACCA")

counts = dna.solve()
dna.printSolution(counts)